name: Test

on:
  merge_group:
    types: [ checks_requested ]
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  test-setup-osc:
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-26, macos-15-intel, windows-2025]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - name: Setup latest OSC (without Authentication)
      uses: ./setup-osc
    - name: Get Version
      shell: bash
      run: |
        LATEST_VERSION=$(gh release view -R eclipse-apoapsis/ort-server --json tagName --jq .tagName)
        [ "$(osc --version)" = "osc version $LATEST_VERSION" ]
    - name: Setup fixed OSC (without Authentication)
      uses: ./setup-osc
      with:
        osc-version: 0.48.0
    - name: Get Version
      shell: bash
      run: |
        [ "$(osc --version)" = "osc version 0.48.0" ]
    - name: Cache fixed OSC (without Authentication)
      id: cache-osc
      uses: ./setup-osc
      with:
        osc-version: 0.48.0
    - name: Verify Cache
      shell: bash
      run: |
        [ "${{ steps.cache-osc.outputs.osc-cached }}" = "true" ]
