name: Test

on:
  merge_group:
    types: [ checks_requested ]
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  test-setup-osc:
    strategy:
      matrix:
        os: [ubuntu-24.04, macos-26, macos-15-intel, windows-2025]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout Repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
    - name: Setup latest OSC (without Authentication)
      uses: ./setup-osc
    - name: Get Version
      shell: bash
      run: |
        LATEST_VERSION=$(curl -s https://api.github.com/repos/eclipse-apoapsis/ort-server/releases/latest | grep '"tag_name"' | cut -d'"' -f4)
        [ "$(osc --version)" = "osc version $LATEST_VERSION" ]
    - name: Setup fixed OSC (without Authentication)
      uses: ./setup-osc
      with:
        osc-version: 0.48.0
    - name: Get Version
      shell: bash
      run: |
        [ "$(osc --version)" = "osc version 0.48.0" ]
    - name: Cache fixed OSC (without Authentication)
      id: cache-osc
      uses: ./setup-osc
      with:
        osc-version: 0.48.0
    - name: Verify Cache
      shell: bash
      run: |
        [ "${{ steps.cache-osc.outputs.osc-cached }}" = "true" ]
